<template>
<div class="start-sign-bg">
    <h1 style="position: absolute; z-index: 13;"><span class="text-pop-up-top ">{{propsHeart*50}}+ </span><span class="text-pop-up-top ">Likes!!!</span></h1>
    <img :src="require(`@/assets/images/rocket.png`)" style="width:300px; z-index: 3;" class="text-pop-up-top ">
</div>
</template>

<script>
export default {
  props: ['propsHeart']
}
</script>


<style>
.text-pop-up-top {
	animation: text-pop-up-top 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  font-size: 5em;
  color: rgb(255, 236, 115);
  -webkit-text-stroke: 1px rgba(255, 88, 88, 0.91);
}
/* ----------------------------------------------
 * Generated by Animista on 2022-8-11 9:51:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-pop-up-top
 * ----------------------------------------
 */
@keyframes text-pop-up-top {
  0% {
    transform: translateY(0);
    transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    transform: translateY(-50px);
    transform-origin: 50% 50%;
    text-shadow: 0 1px 0 #000000, 0 2px 0 #000000, 0 3px 0 #000000, 0 4px 0 #000000, 0 5px 0 #000000, 0 6px 0 #000000, 0 7px 0 #000000, 0 8px 0 #000000, 0 9px 0 #000000, 0 50px 30px rgba(0, 0, 0, 0.3);
  }
}

</style>